-- Huddle Presenca - configuracao inicial do Supabase
-- Execute este arquivo no SQL Editor do novo projeto.
-- Nunca coloque a chave service_role no frontend.

create extension if not exists pgcrypto;

create type public.perfil_usuario as enum ('COLABORADOR', 'LIDER', 'ADMIN');
create type public.status_huddle as enum ('AGENDADO', 'EM_ANDAMENTO', 'ENCERRADO', 'CANCELADO');
create type public.status_presenca as enum ('PRESENTE', 'ATRASADO');

create table if not exists public.setores (
  id uuid primary key default gen_random_uuid(),
  nome text not null unique,
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text not null,
  matricula text not null unique,
  email text,
  perfil public.perfil_usuario not null default 'COLABORADOR',
  setor_id uuid references public.setores(id),
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.huddles (
  id uuid primary key default gen_random_uuid(),
  codigo text not null unique,
  titulo text not null,
  setor_id uuid references public.setores(id),
  responsavel_id uuid not null references public.profiles(id),
  status public.status_huddle not null default 'AGENDADO',
  data_local date not null default current_date,
  iniciado_em timestamptz,
  encerrado_em timestamptz,
  expira_em timestamptz,
  duracao_minutos integer not null default 30,
  atraso_apos_minutos integer not null default 10,
  qr_payload text unique,
  criado_em timestamptz not null default now()
);

create table if not exists public.presencas (
  id uuid primary key default gen_random_uuid(),
  huddle_id uuid not null references public.huddles(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  status public.status_presenca,
  aceite boolean,
  aceite_em timestamptz,
  aceite_texto text,
  aceite_versao text,
  confirmado_em timestamptz,
  criado_em timestamptz not null default now(),
  unique (huddle_id, user_id)
);

create table if not exists public.auditoria_huddle (
  id bigint generated by default as identity primary key,
  huddle_id uuid references public.huddles(id) on delete cascade,
  tabela text not null,
  acao text not null,
  usuario_id uuid references public.profiles(id),
  detalhes jsonb not null default '{}'::jsonb,
  ocorrido_em timestamptz not null default now()
);

create table if not exists public.evidencias_pdf (
  id uuid primary key default gen_random_uuid(),
  huddle_id uuid not null references public.huddles(id) on delete cascade,
  hash_sha256 text not null,
  nome_arquivo text not null,
  tamanho_bytes bigint not null,
  criado_por uuid references public.profiles(id),
  criado_em timestamptz not null default now(),
  unique (huddle_id, hash_sha256)
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, nome, matricula, email, perfil, setor_id)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'nome', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'matricula', 'PENDENTE-' || substr(new.id::text, 1, 8)),
    new.email,
    'COLABORADOR',
    nullif(new.raw_user_meta_data ->> 'setor_id', '')::uuid
  )
  on conflict (id) do update set email = excluded.email;
  return new;
exception when unique_violation then
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at before update on public.profiles
for each row execute procedure public.set_updated_at();

insert into public.setores (nome) values
  ('Administracao'),
  ('Enfermagem'),
  ('Medicina'),
  ('Recepcao')
on conflict (nome) do nothing;

alter table public.setores enable row level security;
alter table public.profiles enable row level security;
alter table public.huddles enable row level security;
alter table public.presencas enable row level security;
alter table public.auditoria_huddle enable row level security;
alter table public.evidencias_pdf enable row level security;

drop policy if exists setores_publicos_ativos on public.setores;
create policy setores_publicos_ativos on public.setores
for select to anon, authenticated using (ativo = true);

drop policy if exists perfil_proprio_select on public.profiles;
create policy perfil_proprio_select on public.profiles
for select to authenticated using (id = auth.uid());

drop policy if exists perfil_proprio_update on public.profiles;
create policy perfil_proprio_update on public.profiles
for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists presencas_proprias_select on public.presencas;
create policy presencas_proprias_select on public.presencas
for select to authenticated using (user_id = auth.uid());

create or replace function public.usuario_e_admin()
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and perfil = 'ADMIN' and ativo = true
  );
$$;

revoke all on function public.usuario_e_admin() from public;
grant execute on function public.usuario_e_admin() to authenticated;

create or replace function public.admin_criar_setor(p_nome text)
returns public.setores
language plpgsql security definer set search_path = public
as $$
declare novo_setor public.setores;
begin
  if not public.usuario_e_admin() then
    raise exception 'Acesso permitido somente para administradores.';
  end if;
  if btrim(coalesce(p_nome, '')) = '' then
    raise exception 'Informe o nome do setor.';
  end if;
  insert into public.setores (nome)
  values (btrim(p_nome))
  returning * into novo_setor;
  return novo_setor;
exception when unique_violation then
  raise exception 'Ja existe um setor com esse nome.';
end;
$$;

revoke all on function public.admin_criar_setor(text) from public;
grant execute on function public.admin_criar_setor(text) to authenticated;

create or replace function public.admin_excluir_setor(p_setor_id uuid)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  if not public.usuario_e_admin() then
    raise exception 'Acesso permitido somente para administradores.';
  end if;

  if not exists (select 1 from public.setores where id = p_setor_id) then
    raise exception 'Setor não encontrado.';
  end if;

  if exists (select 1 from public.profiles where setor_id = p_setor_id)
    or exists (select 1 from public.huddles where setor_id = p_setor_id) then
    raise exception 'Não é possível excluir um setor que possui usuários ou huddles vinculados.';
  end if;

  delete from public.setores where id = p_setor_id;
end;
$$;

revoke all on function public.admin_excluir_setor(uuid) from public;
grant execute on function public.admin_excluir_setor(uuid) to authenticated;

create or replace function public.admin_get_dashboard_v1()
returns json
language plpgsql security definer set search_path = public
as $$
declare resultado json;
begin
  if not public.usuario_e_admin() then
    raise exception 'Acesso permitido somente para administradores.';
  end if;

  select json_build_object(
    'setores', coalesce((select json_agg(x order by x.nome) from (
      select s.id, s.nome, s.ativo,
        (select count(*) from public.profiles p where p.setor_id = s.id) total_usuarios
      from public.setores s
    ) x), '[]'::json),
    'usuarios', coalesce((select json_agg(x order by x.nome) from (
      select p.id, p.nome, p.matricula, u.email,
        p.perfil, p.setor_id, s.nome setor_nome, p.ativo, p.criado_em
      from public.profiles p
      left join public.setores s on s.id = p.setor_id
      left join auth.users u on u.id = p.id
    ) x), '[]'::json)
  ) into resultado;

  return resultado;
end;
$$;

revoke all on function public.admin_get_dashboard_v1() from public;
grant execute on function public.admin_get_dashboard_v1() to authenticated;

create or replace function public.admin_get_presencas_dashboard_v1(
  p_data_inicio date,
  p_data_fim date,
  p_setor_id uuid default null
)
returns json
language plpgsql security definer set search_path = public
as $$
declare resultado json;
begin
  if not public.usuario_e_admin() then
    raise exception 'Acesso permitido somente para administradores.';
  end if;

  with hs as (
    select
      h.id, h.codigo, h.titulo, h.setor_id, s.nome setor_nome,
      h.data_local, h.status, h.responsavel_id, h.iniciado_em,
      h.encerrado_em,
      (select count(*) from public.profiles p where p.setor_id = h.setor_id and p.ativo) total_esperado,
      (select count(*) from public.presencas pr where pr.huddle_id = h.id and pr.confirmado_em is not null) total_confirmado,
      (select count(*) from public.presencas pr where pr.huddle_id = h.id and pr.status = 'PRESENTE') total_presentes,
      (select count(*) from public.presencas pr where pr.huddle_id = h.id and pr.status = 'ATRASADO') total_atrasados
    from public.huddles h
    join public.setores s on s.id = h.setor_id
    where h.data_local between p_data_inicio and p_data_fim
      and (p_setor_id is null or h.setor_id = p_setor_id)
  ), totals as (
    select
      count(*) total_huddles,
      count(*) filter (where status = 'AGENDADO') total_agendados,
      count(*) filter (where status = 'EM_ANDAMENTO') total_em_andamento,
      count(*) filter (where status = 'ENCERRADO') total_encerrados,
      count(*) filter (where status = 'CANCELADO') total_cancelados,
      coalesce(sum(total_esperado), 0) total_esperado,
      coalesce(sum(total_confirmado), 0) total_confirmado,
      coalesce(sum(total_presentes), 0) total_presentes,
      coalesce(sum(total_atrasados), 0) total_atrasados
    from hs
  )
  select json_build_object(
    'periodo', json_build_object('data_inicio', p_data_inicio, 'data_fim', p_data_fim, 'setor_id', p_setor_id),
    'kpis', (select json_build_object(
      'total_huddles', total_huddles, 'total_agendados', total_agendados,
      'total_em_andamento', total_em_andamento, 'total_encerrados', total_encerrados,
      'total_cancelados', total_cancelados, 'total_esperado', total_esperado,
      'total_confirmado', total_confirmado, 'total_presentes', total_presentes,
      'total_atrasados', total_atrasados, 'total_ausentes', greatest(total_esperado - total_confirmado, 0),
      'taxa_participacao', round((100.0 * total_confirmado / nullif(total_esperado, 0))::numeric, 1),
      'taxa_pontualidade', round((100.0 * total_presentes / nullif(total_confirmado, 0))::numeric, 1)
    ) from totals),
    'por_setor', coalesce((select json_agg(x) from (
      select setor_id, setor_nome, true ativo, count(*) total_huddles,
        sum(total_esperado) total_esperado, sum(total_confirmado) total_confirmado,
        sum(total_presentes) total_presentes, sum(total_atrasados) total_atrasados,
        greatest(sum(total_esperado) - sum(total_confirmado), 0) total_ausentes,
        round((100.0 * sum(total_confirmado) / nullif(sum(total_esperado), 0))::numeric, 1) taxa_participacao
      from hs group by setor_id, setor_nome order by setor_nome
    ) x), '[]'::json),
    'evolucao_diaria', coalesce((select json_agg(x order by data) from (
      select data_local data, count(*) total_huddles, sum(total_esperado) total_esperado,
        sum(total_confirmado) total_confirmado, sum(total_presentes) total_presentes,
        sum(total_atrasados) total_atrasados, greatest(sum(total_esperado) - sum(total_confirmado), 0) total_ausentes,
        round((100.0 * sum(total_confirmado) / nullif(sum(total_esperado), 0))::numeric, 1) taxa_participacao
      from hs group by data_local
    ) x), '[]'::json),
    'ultimos_huddles', coalesce((select json_agg(x) from (
      select id huddle_id, codigo, titulo, setor_id, setor_nome, data_local, status,
        (select nome from public.profiles where id = responsavel_id) responsavel_nome,
        iniciado_em, encerrado_em, total_esperado, total_confirmado, total_presentes,
        total_atrasados, greatest(total_esperado - total_confirmado, 0) total_ausentes,
        round((100.0 * total_confirmado / nullif(total_esperado, 0))::numeric, 1) taxa_participacao
      from hs order by data_local desc, iniciado_em desc nulls last limit 20
    ) x), '[]'::json),
    'ranking', '[]'::json
  ) into resultado;
  return resultado;
end;
$$;

revoke all on function public.admin_get_presencas_dashboard_v1(date, date, uuid) from public;
grant execute on function public.admin_get_presencas_dashboard_v1(date, date, uuid) to authenticated;

notify pgrst, 'reload schema';

create or replace function public.get_home_colaborador()
returns json
language sql stable security definer set search_path = public
as $$
  select json_build_object(
    'nome', p.nome,
    'matricula', p.matricula,
    'perfil', p.perfil,
    'setor_id', p.setor_id,
    'setor_nome', s.nome,
    'huddle_id', h.id,
    'huddle_codigo', h.codigo,
    'huddle_titulo', h.titulo,
    'huddle_status', h.status,
    'huddle_data', h.data_local,
    'iniciado_em', h.iniciado_em,
    'atraso_apos', case when h.iniciado_em is null then null else h.iniciado_em + make_interval(mins => h.atraso_apos_minutos) end,
    'expira_em', h.expira_em,
    'presenca_id', pr.id,
    'presenca_status', pr.status,
    'confirmado_em', pr.confirmado_em
  )
  from public.profiles p
  left join public.setores s on s.id = p.setor_id
  left join lateral (
    select * from public.huddles h0
    where h0.status in ('AGENDADO', 'EM_ANDAMENTO')
    order by h0.criado_em desc limit 1
  ) h on true
  left join public.presencas pr on pr.huddle_id = h.id and pr.user_id = p.id
  where p.id = auth.uid();
$$;

grant execute on function public.get_home_colaborador() to authenticated;

create or replace function public.validar_qr_huddle(p_payload text)
returns json
language plpgsql security definer set search_path = public
as $$
declare r public.huddles;
begin
  select * into r from public.huddles where qr_payload = p_payload;
  if not found then raise exception 'QR Code invalido.'; end if;
  return json_build_object(
    'huddle_id', r.id, 'codigo', r.codigo, 'titulo', r.titulo,
    'setor_nome', (select nome from public.setores where id = r.setor_id),
    'data_local', r.data_local, 'iniciado_em', r.iniciado_em,
    'expira_em', r.expira_em,
    'ja_confirmado', exists(select 1 from public.presencas where huddle_id = r.id and user_id = auth.uid())
  );
end;
$$;

grant execute on function public.validar_qr_huddle(text) to authenticated;

create or replace function public.confirmar_presenca_huddle(p_payload text, p_aceite boolean)
returns json
language plpgsql security definer set search_path = public
as $$
declare r public.huddles; v_status public.status_presenca;
begin
  select * into r from public.huddles where qr_payload = p_payload;
  if not found then raise exception 'QR Code invalido.'; end if;
  if r.status not in ('EM_ANDAMENTO', 'AGENDADO') then raise exception 'Este Huddle nao esta disponivel.'; end if;
  v_status := case when r.iniciado_em is not null and now() > r.iniciado_em + make_interval(mins => r.atraso_apos_minutos) then 'ATRASADO' else 'PRESENTE' end;
  insert into public.presencas (huddle_id, user_id, status, aceite, aceite_em, confirmado_em, aceite_texto, aceite_versao)
  values (r.id, auth.uid(), v_status, p_aceite, now(), now(), 'Confirmo minha participacao no Huddle.', '1.0')
  on conflict (huddle_id, user_id) do update set status = excluded.status, aceite = excluded.aceite, aceite_em = now(), confirmado_em = now();
  return json_build_object('huddle_id', r.id, 'status', v_status, 'confirmado_em', now());
end;
$$;

grant execute on function public.confirmar_presenca_huddle(text, boolean) to authenticated;

-- A funcao publica de cadastro usada pelo frontend e a Edge Function:
-- supabase/functions/register-collaborator/index.ts
-- Publique-a com: supabase functions deploy register-collaborator

-- Crie o primeiro administrador manualmente no SQL Editor depois de criar o usuario em Auth:
-- update public.profiles set perfil = 'ADMIN' where id = 'UUID_DO_USUARIO';
